name: '{{context}}'

on: push

jobs:
  terraform-plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      #- name: Setup Terraform CLI
      #  uses: hashicorp/setup-terraform@v1
      #  with:
      #    cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init -no-color

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -no-color