exports.TFResoureTemplate = {
    Context: 'context.tf',
    Terraform: 'terraform.tf',
    Provider_Local: 'provider_local.tf',
    Provider_TFC: 'provider_tfc.tf',
    Storage_S3: 'storage_s3.tf',
    Storage_EFS: 'storage_efs.tf',
    Backend_TFC: 'backend_tfc.tf',
    Backend_S3: 'backend_tfc.tf',
    Backend_Local: 'backend_local.tf',
    GithubCI: 'pipeline_github.yml',
    GitlabCI: 'pipeline_gitlab.yml',
    RemoteState_TFC: 'rstate_tfc.tf',
    RemoteState_S3: 'rstate_s3.tf',
    SNS: 'sns.tf',
    VPC: 'vpc.tf',
    DNSZone: 'dnszone.tf',
    Variable_012: 'variable_0.12.tf',
    Variable_013: 'variable_0.13.tf',
    ProviderAlias_Local: 'provider_alias_local.tf',
    ProviderAlias_TFC: 'provider_alias_tfc.tf',
}